---
output:
  pdf_document: default
  html_document: default
---
---
output:
  pdf_document: default
  html_document: default
---
# Clinical data science - INPer

## Meta-analysis
## Mario I. Lumbreras-Marquez MBBS, MMSc

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Part 1, Dataset**
```{r, warning=FALSE}
library(readxl)
group2_2019 <- read_excel("group2.2019.xlsx")
View(group2_2019)
dat1<-group2_2019
```

**Part 2, Meta-analysis output**
```{r, warning=FALSE}
library(meta)
meta_inper <- metabin(event.e = rds_steroids, n.e = n_steroids, event.c = rds_placebo, 
                      n.c = n_placebo, data = dat1[!is.na(dat1$rds_steroids),], 
                      sm="OR", comb.fixed = T, comb.random = F)
meta_inper
```

**Part 3, Forest plot**
```{r, warning=FALSE, out.width = "70%", fig.align='center', fig.width = 10}
forest(metabin(event.e = rds_steroids, n.e = n_steroids, event.c = rds_placebo, 
               n.c = n_placebo, data = dat1[!is.na(dat1$rds_steroids),], 
               sm="OR", comb.fixed = T, comb.random = F, studlab = Author, 
               prediction = T))
```

**Part 4, Funnel plot**
```{r, warning=FALSE, fig.margin = TRUE}
funnel(metabin(event.e = rds_steroids, n.e = n_steroids, event.c = rds_placebo, 
               n.c = n_placebo, data = dat1[!is.na(dat1$rds_steroids),], 
               sm="OR", comb.fixed = T, comb.random = F))
```
